name: Build JARs
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: JARs
        path: /home/runner/work/JoinMePlus/JoinMePlus/target/*.jar
        retention-days: 7
        
    - name: 'Upload Production Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: Production JAR
        path: /home/runner/work/JoinMePlus/JoinMePlus/target/*-jar-with-dependencies.jar
        retention-days: 7

    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: build # The branch name where you want to push the assets
        FOLDER: /home/runner/work/JoinMePlus/JoinMePlus/target/ # The directory where your assets are generated
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "Build: ({sha}) {msg}" # The commit message
